# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pigeontec
email: frank@pigeontec.com
description: > # this means to ignore newlines until "baseurl:"
  Pigeontec is a web design and web development business based in San Antonio, Texas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pigeontec.com" # the base hostname & protocol for your site
facebook_username: pigeontec
twitter_username:  pigeon_tec
linkedin_username: pigeontec

permalink: /:categories/:title

links:
  -title: about
  url: /about
  -title: process
  url: /process
  -title: menu
  url: /menu
  -title: contact
  url: /contact

# Build settings
markdown: kramdown
